---
engines:
 rubocop:
   enabled: true

pylint:
  enabled: true
  python_version: 3

exclude_paths:
  - '.github/**'
  - '**.md'
  - 'docs/**'
  - evalstats/__init__.py
  - evalstats/__version__.py
  - test/**